### ISSUE TITLE
Mod cause game unable to launch

### ISSUE THREAD

**Issue by Mecnavio** [Jackiecrazy/CloakAndDagger#1]
Game version: 1.18.2
Mod version: 1.0
Forge version: 40.2.4
Installed mod: only Cloak and Dagger
[minecraft-exported-crash-info-2023-05-21T11-20-50.zip](https://github.com/Jackiecrazy/CloakAndDagger/files/11523661/minecraft-exported-crash-info-2023-05-21T11-20-50.zip)

**Comment by Jackiecrazy** [comment]
Install footwork.
