### ISSUE TITLE
1.20.1 dosent work

### ISSUE THREAD

**Issue by jojofenin99** [Jackiecrazy/CloakAndDagger#7]

**Comment by jojofenin99** [comment]
the dependancy mods work but cloak and dagger says it need 1.20 and below

**Comment by SeanChengN** [comment]
![javaw_ZpJp80jjc6](https://github.com/Jackiecrazy/CloakAndDagger/assets/20624068/937d21d9-7053-4bdb-86db-e4dae79375db)

**Comment by Jackiecrazy** [comment]
oh, gah, yikes, so that's what I forgot to do. New version is now uploading.
